import { useState } from 'react';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardActions from '@mui/material/CardActions';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import CircularProgress from '@mui/material/CircularProgress';
import Alert from '@mui/material/Alert';
import Chip from '@mui/material/Chip';
import Divider from '@mui/material/Divider';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import PsychologyIcon from '@mui/icons-material/Psychology';
import RefreshIcon from '@mui/icons-material/Refresh';
import { generateSecurityBriefing } from '../../services/geminiService';

export default function AISecurityBriefing({ ticket }) {
  const [briefing, setBriefing] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [generated, setGenerated] = useState(false);

  const generate = async () => {
    setLoading(true);
    setError('');
    try {
      const text = await generateSecurityBriefing(ticket);
      setBriefing(text);
      setGenerated(true);
    } catch (e) {
      setError(e.message || 'Generation failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card sx={{
      background: 'linear-gradient(135deg, #1A237E 0%, #283593 100%)',
      color: '#fff',
      overflow: 'hidden',
      position: 'relative',
    }}>
      {/* Decorative background circles */}
      <Box sx={{ position: 'absolute', top: -30, right: -30, width: 140, height: 140, borderRadius: '50%', bgcolor: 'rgba(255,255,255,0.05)' }} />
      <Box sx={{ position: 'absolute', bottom: -40, left: -20, width: 100, height: 100, borderRadius: '50%', bgcolor: 'rgba(255,255,255,0.04)' }} />

      <CardContent sx={{ p: 3, position: 'relative', zIndex: 1 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
          <AutoAwesomeIcon sx={{ color: '#FFB300', fontSize: 20 }} />
          <Typography variant="overline" sx={{ color: '#FFB300', letterSpacing: 1.5, lineHeight: 1 }}>
            AI-Powered
          </Typography>
        </Box>
        <Typography variant="h6" fontWeight={700} mb={0.5}>
          Personal Security Briefing
        </Typography>
        <Typography variant="body2" sx={{ opacity: 0.8, mb: 2 }}>
          Generated by Google Gemini · Personalised for your access tier
        </Typography>

        <Chip
          icon={<PsychologyIcon />}
          label="Gemini 1.5 Flash"
          size="small"
          sx={{ bgcolor: 'rgba(255,179,0,0.2)', color: '#FFD54F', border: '1px solid rgba(255,179,0,0.3)', mb: 2 }}
        />

        {!generated && !loading && (
          <Alert
            severity="info"
            sx={{ bgcolor: 'rgba(255,255,255,0.1)', color: '#fff', '& .MuiAlert-icon': { color: '#90CAF9' }, border: 'none', mb: 0 }}
          >
            Your personalised security brief covers entry protocols, zone access rules, and emergency procedures specific to your tier.
          </Alert>
        )}

        {loading && (
          <Box sx={{ textAlign: 'center', py: 3 }}>
            <CircularProgress sx={{ color: '#FFB300' }} size={36} />
            <Typography variant="body2" sx={{ opacity: 0.8, mt: 1.5 }}>
              Generating your personalised briefing…
            </Typography>
          </Box>
        )}

        {error && (
          <Alert severity="error" sx={{ bgcolor: 'rgba(198,40,40,0.2)', color: '#FFCDD2', '& .MuiAlert-icon': { color: '#EF9A9A' } }}>
            {error}
          </Alert>
        )}

        {briefing && (
          <Box sx={{ mt: 2 }}>
            <Divider sx={{ borderColor: 'rgba(255,255,255,0.15)', mb: 2 }} />
            {briefing.split('\n').filter(Boolean).map((para, i) => (
              <Typography key={i} variant="body2" sx={{ opacity: 0.9, mb: 1.5, lineHeight: 1.7 }}>
                {para}
              </Typography>
            ))}
          </Box>
        )}
      </CardContent>

      <CardActions sx={{ p: 3, pt: 0, position: 'relative', zIndex: 1 }}>
        <Button
          variant="contained"
          fullWidth
          onClick={generate}
          disabled={loading}
          startIcon={generated ? <RefreshIcon /> : <AutoAwesomeIcon />}
          sx={{
            bgcolor: '#FFB300',
            color: '#000',
            fontWeight: 700,
            '&:hover': { bgcolor: '#FFA000' },
            '&:disabled': { bgcolor: 'rgba(255,255,255,0.2)', color: 'rgba(255,255,255,0.5)' },
          }}
        >
          {loading ? 'Generating…' : generated ? 'Regenerate Briefing' : 'Generate My Security Briefing'}
        </Button>
      </CardActions>
    </Card>
  );
}
